name: Test

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Gleam compiler
        uses: ./
        with:
          gleam-version: 0.6.0
      - name: Run Gleam compiler
        run: |
          which gleam
          gleam --version

  test_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Gleam compiler
        uses: ./
        with:
          gleam-version: ref:main
      - name: Run Gleam compiler
        run: |
          which gleam
          gleam --version
